name: CRON Release
on:
  push:
    tags:
      - "*v"

permissions:
  contents: write
  packages: write

jobs:
  run-goreleaser:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_ACTIONS_PAT }}
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.21"
      - name: Install Dependencies
        run: |
          go install github.com/charmbracelet/mods@latest
          go install github.com/go-task/task/v3/cmd/task@latest
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser-pro
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}

  run-docker-monolith:
    runs-on: ubuntu-latest
    environment: Staging
    needs: run-goreleaser
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build -t sonrhq/sonr:latest .
          docker push sonrhq/sonr:latest
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
